In [26]:
!pip install numpy

In [27]:
import numpy as np 

In [28]:
Array1 = np.array([1,5,6]) 

print(Array1)

[1 5 6]


In [29]:
Array2= np.array([1,2,3,4,5,6,7,8])

print(Array2.shape) 
                   

(8,)


In [30]:
Matris = Array2.reshape(2,4) 
print(Matris)


[[1 2 3 4]
 [5 6 7 8]]


In [31]:
print("shape: ",Matris.shape)

print("dimension: ",Matris.ndim) 

print("data type: ",Matris.dtype.name) 

print("size: ",Matris.size) 
                       
print("type",type(Matris))  

shape:  (2, 4)
dimension:  2
data type:  int64
size:  8
type <class 'numpy.ndarray'>


In [32]:
ArrayThree= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(ArrayThree)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:
print(ArrayThree.shape) 

(3, 4)


In [34]:
zeros= np.zeros((3,4))  
zeros[0,0]=5
print(zeros)

[[5. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [35]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
np.empty((4,5))

array([[ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316],
       [ 2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211],
       [ 5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105],
       [ 7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ]])

In [37]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [38]:
Array3= np.linspace(0,10,20)
print(Array3)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [39]:

X= np.array([1,2,3])
Y= np.array([4,5,6]) 
print(X+Y) 
print(X-Y)
print(Y**2)

[5 7 9]
[-3 -3 -3]
[16 25 36]


In [40]:
M= np.array([1,2,3,4,5,6,7])
print(M)

[1 2 3 4 5 6 7]


In [41]:
Liste = [1,2,3,4]

Liste_Array = np.array([5,6,7,8]) 
print(Liste_Array)
print(Liste)

[5 6 7 8]
[1, 2, 3, 4]


In [42]:
Array = np.array(Liste)
print(Array)

[1 2 3 4]


In [43]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [44]:
b=a

c=a

b[0]=5
print(a,b,c)

[5 2 3] [5 2 3] [5 2 3]


In [45]:
d = a.copy()
print(d)

[5 2 3]


In [46]:
a= np.array([1,2,3,4,5,6,7]) 
print(a[0])
print(a[0:4])

1
[1 2 3 4]


In [47]:
reverse_array = a[::-1] 
print(reverse_array)

[7 6 5 4 3 2 1]


In [48]:
Arrayw = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(Arrayw)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [49]:
array32 = np.array([[1,2],[3,4],[5,6]])
print(array32)

[[1 2]
 [3 4]
 [5 6]]


In [50]:
array32.resize((2,3)) 
print(array32)

[[1 2 3]
 [4 5 6]]
